services:
  - type: web
    name: sketchme-api
    env: python
    plan: free
    region: oregon
    branch: main
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host=0.0.0.0 --port=10000"
    healthCheckPath: /docs
